### PR TITLE
Add 'Append' abstraction, implementations and tests.

### LINKED ISSUE #1: Add Append function to the KVStoreConnection interface.
So, I want to add Append function to the KVStoreConnection interface. However, currently Set function uses interface{} as a value. And append will work only with certain types, like []byte and string.

The plan is to use that feature as an atomic operations for making lists. E.g. in picfit we can make a list of all the variants of an image by simply appending hashes to an entry which is associated with the original image in KV store.

What do think the best way to do it? Make it work for string and []byte and return error otherwise?

### PR DESCRIPTION
**Pull request by nsf**
Fixes #1.

### CODE REVIEW

**Comment by thoas** [comment]
Thank your for your PR, the implementation of Append is great on both side cache and redis.

But for picfit, I think we can't use the `APPEND` operation as we need to easily iterate children keys of the original images.

This can be only done with a LIST or a SET as APPEND don't provide a clear separator.

```
SADD {original_key}:children "{thumbnail_key}"
```

Your opinion on that?

**Comment by nsf** [comment]
Well, my initial plan was to just invent some separator like `:` or `;` and since we store only hashes, it will work just fine.

But if you think using redis sets is a better idea, then maybe it is. I haven't worked much with redis.

**Comment by nsf** [comment]
I'l try to make an implementation for SetAdd tomorrow in gokvstores. But again, perhaps restrict it to set of string and implement it in cache as `map[string]bool`.

**Comment by thoas** [comment]
I merge this too even if we will not use it for picfit.

:+1:

**Comment by nsf** [comment]
Sure, the change is simple enough and I don't mind of course.

**Pull request merged**
